#!/usr/bin/env python3
"""
Single CLI to update STATUS.json and regenerate the matching sections of
PROJECT.md from it, so the two files can't drift apart.

STATUS.json is the source of truth. The content between the
STATUS_TABLE_START/END and SCENARIO_START/END markers in PROJECT.md is
generated -- edit STATUS.json (via this CLI, or by hand), don't hand-edit
the generated sections directly.

Usage:
    python3 tools/sync_status.py render
    python3 tools/sync_status.py set-part part1_traditional --status in_progress --notes "..."
    python3 tools/sync_status.py set-scenario hospital
"""

import argparse
import datetime
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATUS_PATH = ROOT / "STATUS.json"
PROJECT_PATH = ROOT / "PROJECT.md"

LABELS = {
    "infra_scaffold": "Infra scaffold",
    "scenario_selection": "Scenario selection",
    "part1_traditional": "Part 1 -- Traditional",
    "part2_faas": "Part 2 -- FaaS",
    "part3_feature_extension": "Part 3 -- Feature extension",
    "part4_performance": "Part 4 -- Performance",
    "part5_security_maintainability": "Part 5 -- Security/Maintainability",
    "report": "Report",
}

STATUS_DISPLAY = {
    "not_started": "Not started",
    "in_progress": "In progress",
    "done": "Done",
    "optional_not_started": "Optional, not started",
    "optional_in_progress": "Optional, in progress",
    "optional_done": "Optional, done",
}


def load_status() -> dict:
    return json.loads(STATUS_PATH.read_text())


def save_status(data: dict) -> None:
    data["last_updated"] = datetime.date.today().isoformat()
    STATUS_PATH.write_text(json.dumps(data, indent=2) + "\n")


def render_table(data: dict) -> str:
    lines = ["| Part | Status | Notes |", "|---|---|---|"]
    for key, part in data["parts"].items():
        label = LABELS.get(key, key)
        status = STATUS_DISPLAY.get(part["status"], part["status"])
        notes = part.get("notes", "")
        lines.append(f"| {label} | {status} | {notes} |")
    return "\n".join(lines)


def render_scenario(data: dict) -> str:
    scenario = data.get("scenario")
    if scenario:
        return f"**{scenario}**"
    options = ", ".join(data.get("scenario_options", []))
    return f"**Not yet chosen.** Options considered: {options}."


def _replace_between(text: str, start_marker: str, end_marker: str, body: str) -> str:
    pattern = re.compile(re.escape(start_marker) + r".*?" + re.escape(end_marker), re.DOTALL)
    replacement = f"{start_marker}\n{body}\n{end_marker}"
    new_text, count = pattern.subn(replacement, text)
    if count != 1:
        raise SystemExit(f"expected exactly one {start_marker!r}...{end_marker!r} block, found {count}")
    return new_text


def render() -> None:
    data = load_status()
    project = PROJECT_PATH.read_text()

    project = _replace_between(
        project,
        "<!-- STATUS_TABLE_START (generated by tools/sync_status.py from STATUS.json - do not hand-edit) -->",
        "<!-- STATUS_TABLE_END -->",
        render_table(data),
    )
    project = _replace_between(
        project,
        "<!-- SCENARIO_START -->",
        "<!-- SCENARIO_END -->",
        render_scenario(data),
    )

    PROJECT_PATH.write_text(project)


def cmd_render(args: argparse.Namespace) -> None:
    render()


def cmd_set_part(args: argparse.Namespace) -> None:
    data = load_status()
    if args.part not in data["parts"]:
        raise SystemExit(f"unknown part {args.part!r}; known parts: {', '.join(data['parts'])}")
    data["parts"][args.part]["status"] = args.status
    if args.notes is not None:
        data["parts"][args.part]["notes"] = args.notes
    save_status(data)
    render()


def cmd_set_scenario(args: argparse.Namespace) -> None:
    data = load_status()
    data["scenario"] = args.name
    save_status(data)
    render()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("render", help="regenerate PROJECT.md from STATUS.json").set_defaults(func=cmd_render)

    p = sub.add_parser("set-part", help="update one part's status/notes, then regenerate")
    p.add_argument("part")
    p.add_argument("--status", required=True, choices=list(STATUS_DISPLAY))
    p.add_argument("--notes")
    p.set_defaults(func=cmd_set_part)

    p = sub.add_parser("set-scenario", help="set the chosen scenario, then regenerate")
    p.add_argument("name")
    p.set_defaults(func=cmd_set_scenario)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
